project_name: cwe
builds:
  - binary: cwe
    main: ./cmd/cwe/main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - x86
    ldflags: -extldflags "-static" -s -w -X github.com/monobuild/cwe/cmd/cwe/methods.versionNumber={{.Version}} -X github.com/monobuild/cwe/cmd/cwe/methods.commit={{.Commit}} -X github.com/monobuild/cwe/cmd/cwe/methods.date={{.Date}}
    env:
    - CGO_ENABLED=0

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{.Commit}}

nfpm:
    vendor: Sascha Andres
    homepage: https://livingit.de
    maintainer: Sascha Andres <sascha.andres@outlook.com>
    description: utility to call other processes with additional environment variables
    license: Apache 2.0
    formats:
      - deb
    dependencies:
      - git
    bindir: /usr/bin

release:
  draft: true
  github:
      owner: sascha-andres
      name: cwe

